### ISSUE TITLE
Conflicting indentation between prettier-standard and eslint

### ISSUE THREAD

**Issue by binkymilk** [thinkingmachines/coding-style#15]
Found a bug wherein indentation styles were different between `prettier-standard` and `eslint`:

```
const label = selectedItem
     ? selectedItem.label
     : defaultValue
-    ? defaultValue.label
-    : placeholder || 'Select...'
+      ? defaultValue.label
+      : placeholder || 'Select...'
```

A temporary fix was done by disabling indent in `eslint` and should be removed once this bug is fixed. (related issue: [#66](https://github.com/thinkingmachines/asimov/issues/66))

**Comment by jtmiclat** [comment]
Basic `.eslintrc` to get `prettier-standard` and `eslint` to work 
```
{
  "extends": ["standard", "prettier"]
}
```

Not sure if we should add the following to the dependencies or let users install that themselves using additional dependencies
```
- eslint-config-prettier
- eslint-config-standard
- eslint-plugin-import
- eslint-plugin-node 
- eslint-plugin-prettier
- eslint-plugin-promise
- eslint-plugin-standard
```
