### ISSUE TITLE
Tag 2020.04.17 doesn't exist yet

### ISSUE THREAD

**Issue by enerve** [thinkingmachines/coding-style#20]
I used the latest .pre-commit-config.yaml from README.
However it appears that tag/release 2020.04.17 doesn't yet exist on the repo.
I will try with 2020.03.31

**Comment by jtmiclat** [comment]
Thanks for reporting! Seems like we didnt release a 2020.04.17 version so this is docs. Will udpate docs to use 2020.03.31
